"""Build + execute TransformerSac/interp_walkthrough.ipynb.

The walkthrough teaches the interp pipeline (capture -> probe -> steer) in
depth on the delmax2x2_B_pen_s1 artifacts. Every notebook cell runs OFFLINE
(no env construction): the capture npz stores the exact actor input tensors,
so replay, probing, PCA and steering all run through the bare actor in
milliseconds.

This script defines the cells, executes the notebook with nbclient (kernel
cwd = TransformerSac/, venv kernel), and writes the executed .ipynb with all
outputs embedded. Any cell error aborts the build loudly.

Usage (from TransformerSac/):
    ../.venv/bin/python interp/make_walkthrough.py
"""

import os
import sys
import time

import nbformat
from nbclient import NotebookClient

_INTERP_DIR = os.path.dirname(os.path.abspath(__file__))
TSAC_DIR = os.path.dirname(_INTERP_DIR)
OUT_PATH = os.path.join(TSAC_DIR, "interp_walkthrough.ipynb")

# ---------------------------------------------------------------------------
# Cells: ("md" | "code", source). Markdown-heavy by design -- the notebook is
# a tutorial, not a script.
# ---------------------------------------------------------------------------

CELLS = [

# ============================ 0. title ====================================
("md", r"""
# Mechanistic interpretability of the derating agent — an end-to-end walkthrough

This notebook teaches the `interp/` pipeline from scratch: the concepts
behind each stage, the mechanics of the code, and what the results on
**`delmax2x2_B_pen_s1`** (the DEL-penalized 2×2 yaw+derate checkpoint) mean.
It assumes you know RL and transformers, and assumes **zero** interpretability
background.

Two things make this notebook fast enough to re-run top to bottom in under a
couple of minutes:

1. The Stage-1 capture stored the **exact input tensors fed to the actor** at
   every step of a closed-loop rollout. Everything downstream — replay,
   probing, PCA, even steering sweeps — can therefore run through the bare
   actor network offline, in milliseconds, with no wind-farm simulator.
2. The expensive closed-loop experiments were already run by the CLI scripts;
   we load their artifacts and only *re-derive the cheap parts live* so you
   can see how every number is produced.

> Generated by `interp/make_walkthrough.py` — edit that script and re-run it
> to regenerate or extend this notebook.
"""),

# ============================ 1. big picture ==============================
("md", r"""
## 1. The big picture: what question are we asking?

Ordinary evaluation treats the policy as a black box: feed observations,
score the actions. Mechanistic interpretability opens the box and asks *what
is computed inside*: which internal quantities does the network represent,
where, and does the computation actually **use** them — could we grab one and
turn it like a knob?

The pipeline follows the standard three-step empirical loop of the field:

| Stage | Question | Method | Epistemic status |
|---|---|---|---|
| **1. Capture** | What do the internals look like while the policy acts? | forward hooks on a closed-loop rollout | observation |
| **2. Probe** | Is behavior linearly readable from the internals? Where? | PCA, ridge probes, difference-of-means | **correlation** |
| **3. Steer** | Does moving the internals move the behavior? | activation addition, closed-loop sweep | **causation** |

The distinction in the last column is the heart of the matter. A probe that
predicts behavior from activations proves only that the *information* is
present. Steering — writing into the activations and watching behavior change
— is the causal experiment that tests whether the network's own computation
runs through the thing we found.

### Why this agent is a good subject

`delmax2x2_B_pen_s1` was trained with a hinge penalty on fatigue loads
(damage-equivalent loads, DEL): whenever the farm's worst-turbine DEL exceeds
a threshold relative to a greedy baseline farm, reward is docked. The agent
learned to **derate** — sacrifice power to protect the turbines. Its sibling
run `delmax2x2_A_nopen` (no penalty) barely derates at all.

So the penalty *trained a safety behavior into the weights*. That makes three
questions concrete:

- **Where** does "how conservative am I being?" live inside the network?
- Is it a simple **direction** in activation space, or something diffuse?
- Can we **dial** it at deployment time — more/less conservative — without
  retraining, and what power/load trade-off does the dial trace?

This is a miniature, fully-inspectable analogue of steering safety-relevant
behaviors in large language models — with the advantage that here the
behavior has physical units (MW, load ratios) and a ground-truth simulator.

### Artifact map

Everything this notebook loads was produced by three CLI scripts (commands in
the appendix):

```text
runs/delmax2x2_B_pen_s1/checkpoints/step_400020.pt   the trained policy
data/interp/delmax2x2_B_pen_s1/
    capture_limnone_s0.npz          Stage 1  activations + exact actor inputs
                                             + behavior labels, 1320 steps
    directions/direction_{site}.npz Stage 2  steering vector per hook site
    steer/steer_final_norm_s0.npz   Stage 3  closed-loop steering sweep
figs/interp/delmax2x2_B_pen_s1/*.png         figures from stages 2-3
```
"""),

# ============================ 2. the policy ===============================
("md", r"""
## 2. The policy under the microscope

The actor is a **transformer over turbine tokens**: each turbine contributes
one token (its own 60-dim observation vector: wind/power/yaw/derate sensor
histories), the transformer lets turbines attend to each other (that is where
wake interactions enter), and a shared linear head reads each token out into
that turbine's 2-dim action `[yaw, derate]`. Sharing the head across tokens
makes the policy permutation-equivariant.

We start by rebuilding the actor **from the checkpoint alone** — no
environment. This is worth doing once by hand because it makes a point that
underlies the whole pipeline: *the checkpoint contains everything*. The
state-dict's weight **shapes** encode the architecture dimensions, and the
action-scaling constants were saved as buffers inside the network itself.
"""),

("code", r"""
%matplotlib inline
import json, os, sys
for p in (os.path.abspath(".."), os.path.abspath(".")):
    if p not in sys.path:
        sys.path.insert(0, p)

import numpy as np
import torch
import matplotlib.pyplot as plt

plt.rcParams.update({"figure.dpi": 110, "axes.grid": True, "grid.alpha": 0.3,
                     "axes.axisbelow": True})

# interp.common imports the full training stack (WindGym, DWM, DEL surrogate)
# because its OTHER helpers rebuild envs. We only use load_checkpoint here --
# nothing in this notebook constructs an environment.
from interp.common import load_checkpoint, DERATE_COL, YAW_COL

device = torch.device("cpu")
RUN = "delmax2x2_B_pen_s1"
CKPT = f"runs/{RUN}/checkpoints/step_400020.pt"
DATA = f"data/interp/{RUN}"

checkpoint, args = load_checkpoint(CKPT, device)
sd = checkpoint["actor_state_dict"]

print(f"\ncheckpoint: {CKPT}")
print(f"  training step   : {checkpoint['step']:,}")
print(f"  config          : {args['config']}  (layout {args['layouts']})")
print(f"  transformer     : {args['num_layers']} layers, embed_dim={args['embed_dim']}, "
      f"{args['num_heads']} heads")
print(f"  DEL penalty     : scale={args['del_penalty_scale']}, "
      f"allowed_increase={args['del_allowed_increase']}")
print(f"  actor state dict: {len(sd)} tensors")
"""),

("md", r"""
### Rebuilding the actor offline

`interp.common.build_actor` needs a live env (it reads the obs width and
action bounds from the env's spaces). But every one of those numbers is also
in the checkpoint:

- `obs_encoder.0.weight` has shape `(embed_dim, obs_width)` → **60** obs
  features per turbine;
- `fc_mean.weight` has shape `(action_dim, embed_dim)` → **2** actions per
  turbine (yaw = column 0, derate = column 1 — the `YAW_COL`/`DERATE_COL`
  convention);
- `action_scale` / `action_bias_val` were registered as **buffers**, so the
  tanh-squash constants ride along inside the state dict.

Everything else (layer count, head count, positional-encoding flavor, profile
encoders) comes from the `args` namespace stored in the checkpoint. And
`load_state_dict` is itself the correctness check: it raises if any shape
disagrees.
"""),

("code", r"""
from argparse import Namespace
from networks import TransformerActor, create_profile_encoding


def build_actor_offline(args, checkpoint, device=torch.device("cpu")):
    '''Rebuild the TransformerActor from the checkpoint ALONE (no env).'''
    sd = checkpoint["actor_state_dict"]
    obs_dim = sd["obs_encoder.0.weight"].shape[1]    # 60 obs features / turbine
    action_dim = sd["fc_mean.weight"].shape[0]       # 2 actions / turbine
    action_scale = sd["action_scale"].cpu().numpy()  # saved buffers -> no env needed
    action_bias = sd["action_bias_val"].cpu().numpy()

    shared_recep = shared_influ = None
    if args["profile_encoding_type"] is not None and args["share_profile_encoder"]:
        shared_recep, shared_influ = create_profile_encoding(
            profile_type=args["profile_encoding_type"],
            embed_dim=args["embed_dim"],
            hidden_channels=args["profile_encoder_hidden"],
        )

    a = Namespace(**args)
    actor = TransformerActor(
        obs_dim_per_turbine=obs_dim,
        action_dim_per_turbine=action_dim,
        embed_dim=a.embed_dim, pos_embed_dim=a.pos_embed_dim,
        num_heads=a.num_heads, num_layers=a.num_layers,
        mlp_ratio=a.mlp_ratio, dropout=0.0,
        action_scale=action_scale, action_bias=action_bias,
        pos_encoding_type=a.pos_encoding_type,
        rel_pos_hidden_dim=a.rel_pos_hidden_dim,
        rel_pos_per_head=a.rel_pos_per_head,
        pos_embedding_mode=a.pos_embedding_mode,
        profile_encoding=a.profile_encoding_type,
        profile_encoder_hidden=a.profile_encoder_hidden,
        n_profile_directions=a.n_profile_directions,
        profile_fusion_type=a.profile_fusion_type,
        profile_embed_mode=a.profile_embed_mode,
        shared_recep_encoder=shared_recep,
        shared_influence_encoder=shared_influ,
        args=a,
    ).to(device)
    actor.load_state_dict(sd)   # raises on ANY shape mismatch -- the correctness check
    return actor.eval()


actor = build_actor_offline(args, checkpoint, device)
print(f"total parameters: {sum(p.numel() for p in actor.parameters()):,}\n")
for name, mod in actor.named_children():
    n = sum(p.numel() for p in mod.parameters())
    print(f"  {name:20s} {type(mod).__name__:26s} {n:>9,} params")
"""),

("md", r"""
### The residual stream, and where we tap it

The transformer body is **pre-norm**: each sublayer computes its update from
a LayerNorm'd copy of the token vector and then **adds** the result back:

```text
x = x + Attn(LN(x))        # attention sublayer
x = x + MLP(LN(x))         # feed-forward sublayer
```

Because every sublayer only ever *adds* into `x`, the running 128-dim vector
per token is called the **residual stream**. Think of it as a shared
communication bus: the embedding writes the initial content, each sublayer
reads the bus, computes something, and writes its contribution back by
addition, and at the very end the action head reads the bus. Nothing along
the way overwrites — everything accumulates. That additive structure is what
makes the two core operations of this pipeline natural:

- **reading** the stream at any depth is meaningful (it is the sum of
  everything computed so far), and
- **writing** into it (adding a vector) is exactly the kind of edit the
  network's own sublayers perform on every forward pass.

Data flow through this particular actor, with the five capture sites marked
`[...]`:

```text
per-turbine obs (60) ──▶ obs_encoder MLP ─────────────▶ [embed]      (T,128)
wake roses (recep + influ, 360 dirs) ─▶ Fourier enc ─▶ (+) ─▶ profile_embed
[embed] ⧺ profile_embed ──▶ profile_proj (256→128) ──▶ [tok_in]     stream entry
positions (2) ──▶ rel-pos MLP ──▶ attention bias   (enters the attention
                                                    scores, NOT the stream)

[tok_in] ── layer 0: x += Attn(LN(x)); x += MLP(LN(x)) ──▶ [resid_L0]
         ── layer 1:            same                   ──▶ [resid_L1]
[final_norm] = LayerNorm(x) ──▶ fc_mean / fc_logstd ──▶ tanh ──▶ [yaw, derate]
```

| site | what it is | why it matters |
|---|---|---|
| `embed` | obs-encoder output | what a turbine knows from **its own sensors alone** |
| `tok_in` | transformer input | stream entry: obs + wake-geometry profiles fused |
| `resid_L0` | after layer 0 | one round of turbine-to-turbine attention |
| `resid_L1` | after layer 1 | full depth, pre-norm |
| `final_norm` | after the final LayerNorm | what `fc_mean` **directly reads** — the most surgical steering point, since nothing re-normalizes after it |

All sites are `(batch, n_tokens, 128)` tensors; on the 2×2 layout there are
T = 4 tokens per step.
"""),

# ============================ 3. capture ==================================
("md", r"""
## 3. Stage 1 — capture: recording the stream in flight

### Forward hooks in three lines

PyTorch lets you register a callback on any `nn.Module` that fires on every
forward pass with the module's inputs and output. A hook that only *stores* a
detached reference observes the computation without perturbing it:
"""),

("code", r"""
probe_layer = torch.nn.Linear(3, 2)
captured = {}

def grab(module, inputs, output):
    captured["out"] = output.detach()   # detach: read-only, never touches the graph

handle = probe_layer.register_forward_hook(grab)
_ = probe_layer(torch.randn(5, 3))
handle.remove()                          # hooks are global state -- always remove
print("captured:", tuple(captured["out"].shape))
"""),

("md", r"""
`interp.hooks.ActivationCapture` is exactly this, wrapped in a context
manager (so removal can't be forgotten) and pointed at the five sites. Two
mechanical subtleties are worth knowing because they *will* bite anyone who
re-implements this:

- **Site kinds.** The transformer layers return a **tuple** `(x,
  attn_weights)`, so their hook must read `output[0]` — and a *steering* hook
  must rebuild the whole tuple, or `need_weights=True` code paths break.
  `tok_in` is different again: it is a `forward_pre_hook` on the transformer
  (capturing the *input*, i.e. the stream entry), because no single module
  "outputs" that tensor.
- **Read-only means read-only.** The capture hooks return `None`, so PyTorch
  keeps the original outputs; a capture-on rollout is bit-identical to a
  capture-off rollout.

### Why closed-loop capture?

We could feed the actor random observations and record activations. But the
question is what the network computes **on the states it actually visits**
when controlling the farm — activations off the visited-state manifold can
look arbitrarily different. So Stage 1 rolls the policy itself (deterministic
mean action) in its own training env — 4-turbine DWM simulation with the
greedy-baseline reference farm running in parallel for the DEL labels — and
records at every step:

1. the five activation sites,
2. **the exact input tensors fed to the actor** (obs, wind-relative
   positions, padding mask, wake profiles),
3. the policy outputs (sampled + mean action, log-std),
4. behavior and outcome labels.

Item 2 is the design decision this whole notebook rides on: with the true
inputs stored, the actor can be re-run offline at any time, and steering
experiments become millisecond-scale batched forward passes.

The labels follow a SARSA-like pairing: the activations of row *t* were
computed from the *pre-step* state, the row's outcome labels (power, DEL
ratio, reward) are measured *after* `env.step(action_t)`. Each row is one
(state, activations, action, outcome) tuple.
"""),

("code", r"""
z = np.load(f"{DATA}/capture_limnone_s0.npz")
meta = json.loads(str(z["metadata_json"]))
print(f"capture: {meta['episodes']} episodes x ({meta['warmup']} warmup + "
      f"{meta['steps']} steps) on {meta['layout']}, deterministic policy, "
      f"git {meta['git_rev']}\n")

groups = {
    "activations, one per site (S, T, 128)":
        [k for k in z.files if k.startswith("act_")],
    "exact actor inputs (the replay contract)":
        ["obs", "positions", "mask", "recep", "influ"],
    "policy outputs":
        ["action", "mean_action", "log_std"],
    "behavior labels, per turbine (S, T)":
        ["derate_cmd", "derate_real", "yaw", "power_per_turbine",
         "loads", "loads_baseline"],
    "outcome labels, per step (S,)":
        ["power_agent", "power_baseline", "reward", "reward_unpenalized",
         "del_ratio", "del_margin", "del_limit", "del_penalty", "ws", "wd", "ti"],
    "bookkeeping":
        ["episode_idx", "episode_step", "is_warmup"],
}
for title, keys in groups.items():
    print(title)
    for k in keys:
        print(f"    {k:20s} {str(z[k].shape):16s} {z[k].dtype}")

S, T = z["obs"].shape[:2]
keep = ~z["is_warmup"]           # drop DEL-warmup steps from all analysis
print(f"\nS = {S} rows, T = {T} turbine tokens; "
      f"{int(keep.sum())} post-warmup rows enter the analysis")
"""),

("md", r"""
### The determinism contract

If the saved inputs are really *exact*, then running the actor on them must
reproduce the saved `mean_action`. This replay is the pipeline's foundational
sanity check — it proves simultaneously that (a) the npz is sufficient for
every offline experiment below, and (b) the capture hooks did not perturb the
policy.

Why is the tolerance `5e-6` and not `0`? The rollout ran the actor with batch
size 1; the replay batches all 1320 rows at once. Batched float32 matrix
multiplies sum in a different order, and float addition is not associative —
so results drift by ~1e-6. A *real* input mismatch (wrong normalization,
stale profile, shifted row) produces errors orders of magnitude larger, so
the tight-but-nonzero tolerance separates the two cleanly.
"""),

("code", r"""
def squash(mean):
    '''pre-squash mean -> env-units action, exactly as get_action does.'''
    return torch.tanh(mean) * actor.action_scale + actor.action_bias_val

with torch.no_grad():
    mean, log_std, _ = actor.forward(
        torch.as_tensor(z["obs"]), torch.as_tensor(z["positions"]),
        torch.as_tensor(z["mask"]), torch.as_tensor(z["recep"]),
        torch.as_tensor(z["influ"]) if actor.use_influence else None)
    mean_action = squash(mean).numpy()

max_diff = np.abs(mean_action - z["mean_action"]).max()
print(f"replayed all {S} steps in one batch: max |mean_action diff| = {max_diff:.2e}")
assert max_diff <= 5e-6, "determinism contract violated"
print("replay OK -- the npz alone reproduces the rollout's policy outputs")

# Bonus: the derate action channel is a linear map to the derate command.
cmd = 0.1 * (z["action"][..., DERATE_COL] + 1.0)
print(f"derate_cmd == 0.1 * (action + 1): max dev {np.abs(cmd - z['derate_cmd']).max():.1e}"
      "\n  (raw action -1 = run at full power, +1 = the 20% derate cap)")
"""),

("md", r"""
### What the agent is actually doing

Before hunting inside the network, look at the behavior we want to explain.
The penalized agent derates *selectively* — the farm-mean derate command
moves around a few percent, spiking when loads run hot — and holds the DEL
ratio (worst-turbine fatigue load relative to the greedy baseline farm)
around its allowed limit.
"""),

("code", r"""
fig, axes = plt.subplots(1, 2, figsize=(11, 3.6))

ax = axes[0]
for ep in range(meta["episodes"]):
    row = z["episode_idx"] == ep
    ax.plot(z["episode_step"][row], z["derate_cmd"][row].mean(axis=1),
            color=plt.cm.viridis(ep / max(meta["episodes"] - 1, 1)),
            lw=1.3, label=f"episode {ep}")
ax.axvspan(0, meta["warmup"], color="gray", alpha=0.15, lw=0)
ax.text(meta["warmup"] / 2, ax.get_ylim()[1] * 0.9, "warmup", ha="center",
        fontsize=8, color="gray")
ax.set_xlabel("episode step")
ax.set_ylabel("farm-mean derate command")
ax.set_title("behavior: how much the agent derates")
ax.legend(fontsize=7, ncol=2)

ax = axes[1]
good = keep & np.isfinite(z["del_ratio"])
ax.hist(z["del_ratio"][good], bins=40, color="C0")
ax.axvline(float(np.nanmean(z["del_limit"][keep])), color="C3", ls="--",
           label="DEL limit (hinge penalty starts)")
ax.set_xlabel("DEL ratio (agent worst-turbine / baseline)")
ax.set_ylabel("steps")
ax.set_title("outcome: fatigue load vs baseline")
ax.legend(fontsize=8)

fig.tight_layout()
plt.show()
"""),

# ============================ 4. PCA ======================================
("md", r"""
## 4. Looking for structure: PCA on the stream

First-principles refresher. Take the token activations at one site as a
matrix $X \in \mathbb{R}^{N \times 128}$ (rows = turbine-steps). Center the
columns and take the SVD, $X_c = U S V^\top$. The rows of $V^\top$ are the
**principal components**: orthogonal directions in activation space, sorted
by how much variance of the data they carry ($S^2/N$). Projecting each token
onto the first two gives the best possible 2-D "map" of where activations
lie, in the least-squares sense.

PCA is **unsupervised** — it never sees our labels. So a useful trick is to
compute the map from activations alone, then *color* it with a label. If the
color forms a gradient across the map, the label's information sits in the
high-variance directions of the representation; the network "spends
capacity" on it.
"""),

("code", r"""
site = "final_norm"
X = z["act_" + site][keep].reshape(-1, 128)     # (N_tokens, 128)
y_cmd = z["derate_cmd"][keep].reshape(-1)       # per-token derate command
y_ratio = np.repeat(z["del_ratio"][keep], T)    # step label broadcast to tokens
y_turb = np.tile(np.arange(T), int(keep.sum())) # token identity

Xc = X - X.mean(axis=0)
U, s, Vt = np.linalg.svd(Xc, full_matrices=False)
var = s**2 / (s**2).sum()
pcs = Xc @ Vt[:2].T
print(f"{site}: N = {len(X)} tokens; variance in PC1 = {var[0]:.0%}, "
      f"PC2 = {var[1]:.0%} (of 128 dims)")

fig, axes = plt.subplots(1, 3, figsize=(13.5, 3.9), sharex=True, sharey=True)
for ax, c, name in [(axes[0], y_cmd, "derate command"),
                    (axes[1], y_ratio, "DEL ratio")]:
    good = np.isfinite(c)
    scpl = ax.scatter(pcs[good, 0], pcs[good, 1], c=c[good], s=4, alpha=0.5,
                      cmap="viridis")
    fig.colorbar(scpl, ax=ax, label=name)
    ax.set_title(f"colored by {name}")
    ax.set_xlabel(f"PC1 ({var[0]:.0%} var)")
axes[0].set_ylabel(f"PC2 ({var[1]:.0%} var)")

ax = axes[2]
for tI in range(T):
    m = y_turb == tI
    ax.scatter(pcs[m, 0], pcs[m, 1], s=4, alpha=0.5, color=plt.cm.tab10(tI),
               label=f"turbine {tI}")
ax.set_title("colored by turbine index")
ax.set_xlabel(f"PC1 ({var[0]:.0%} var)")
ax.legend(fontsize=7, markerscale=2)
fig.tight_layout()
plt.show()
"""),

("md", r"""
### Reading the map — and its limits

Two observations, and what they do / do not imply:

- **The derate gradient.** Derate command varies smoothly across the leading
  PCs, i.e. the behavior we care about is aligned with directions the
  representation dedicates real variance to. This is encouraging but purely
  **correlational** — it says the information is *visible*, not that any
  downstream computation *uses* those directions, and not that the
  relationship is linear.
- **Turbine clustering.** Tokens organize by turbine identity (front-row vs
  waked turbines live in different regions). That is expected — upstream and
  downstream turbines face genuinely different local physics — but it warns
  us that a single farm-wide "conservativeness direction" is a
  simplification: whatever we extract will average over turbine roles.
  (The per-turbine `turbine_mask` seam in `SteeringHook` exists for exactly
  this follow-up.)

PCA finds the *biggest* directions, not the *relevant* ones. To ask a sharper
question — "is the behavior **linearly readable**, and where?" — we need
probes.
"""),

# ============================ 5. probes ===================================
("md", r"""
## 5. Stage 2a — linear probes: where is the signal readable?

### The linear representation hypothesis

A recurring empirical finding in deep networks (from Alain & Bengio's probe
paper through modern LLM interpretability) is that networks tend to encode
interpretable features as **directions** in activation space: the amount of a
feature ≈ a dot product $\langle x, w\rangle$ with some fixed vector $w$.
It is a hypothesis, not a law — but it is cheap to test and, where it holds,
it hands us both a *readout* (probing) and a *write handle* (steering).

The test: fit a **ridge regression** from activations to a behavior label at
each site and compare held-out $R^2$. Ridge rather than OLS because 128
correlated dimensions with a few thousand samples invites overfitting;
the L2 penalty (α=10) keeps the probe honest.

### Two methodological guards

- **Grouped cross-validation.** Consecutive simulator steps are heavily
  autocorrelated: activations at $t$ and $t{+}1$ are near-duplicates. Random
  K-fold would place near-copies of test rows in the training set, and the
  probe's $R^2$ would measure *memorization of the rollout*, not readability
  of the feature. We therefore split by **episode**: a probe is scored only
  on episodes it never saw.
- **Shuffle control.** Refit each probe on label-shuffled data. This severs
  the X→y relationship while keeping both marginals; if the shuffled probe
  scores materially above zero, the evaluation is leaking and no result can
  be trusted.
"""),

("code", r"""
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score
from sklearn.model_selection import GroupKFold

SITES = ["embed", "tok_in", "resid_L0", "resid_L1", "final_norm"]
y = z["derate_cmd"][keep].reshape(-1)
groups_ep = np.repeat(z["episode_idx"][keep], T)     # fold by EPISODE

def probe_r2(X, y, groups, ridge_alpha=10.0, shuffle=False, seed=0):
    if shuffle:
        y = np.random.default_rng(seed).permutation(y)
    scores = []
    for tr, te in GroupKFold(n_splits=5).split(X, y, groups):
        model = Ridge(alpha=ridge_alpha).fit(X[tr], y[tr])
        scores.append(r2_score(y[te], model.predict(X[te])))
    return float(np.mean(scores))

ladder = {}
print(f"{'site':12s} {'R^2':>8s} {'shuffled':>10s}")
for s_ in SITES:
    Xs = z["act_" + s_][keep].reshape(-1, 128)
    ladder[s_] = (probe_r2(Xs, y, groups_ep),
                  probe_r2(Xs, y, groups_ep, shuffle=True))
    print(f"{s_:12s} {ladder[s_][0]:+8.3f} {ladder[s_][1]:+10.3f}")
"""),

("code", r"""
xs = np.arange(len(SITES))
fig, ax = plt.subplots(figsize=(7.2, 3.6))
ax.bar(xs - 0.2, [ladder[s_][0] for s_ in SITES], 0.38, color="C0",
       label="probe $R^2$ (grouped CV)")
ax.bar(xs + 0.2, [ladder[s_][1] for s_ in SITES], 0.38, color="lightgray",
       label="shuffled-label control")
ax.axhline(0, color="k", lw=0.8)
ax.set_xticks(xs)
ax.set_xticklabels(SITES)
ax.set_ylabel("held-out $R^2$")
ax.set_title("where 'how much am I derating?' becomes linearly readable")
ax.legend(fontsize=8)
fig.tight_layout()
plt.show()
"""),

("md", r"""
### Reading the ladder

The $R^2$ ladder climbs from ≈ 0 at `embed` to ≈ 0.75 at `final_norm` (the
stored Stage-2 artifacts record the same ladder: 0.01 → 0.05 → −0.13 → 0.39
→ 0.75). Three lessons:

1. **The conservativeness signal is *computed*, not sensed.** At `embed` — a
   turbine's own 60 sensor features, before any cross-turbine communication —
   the derate command is essentially unreadable. Only after the attention
   layers mix information across turbines (wake geometry, who is loading
   whom) does a linear readout emerge. The behavior is a product of the
   transformer's turbine-to-turbine computation.
2. **A negative $R^2$ is informative, not a bug.** At `resid_L0` the probe
   generalizes *worse than predicting the mean*. Under grouped CV that means
   the probe latches onto episode-specific structure in mid-stream
   activations that doesn't transfer across episodes — a nice demonstration
   of exactly the leakage that grouped CV exists to expose (random folds
   would have happily reported a large positive number here).
3. **The `final_norm` row is near-trivial — by design of the architecture.**
   `fc_mean` reads `final_norm` linearly and the derate command is a
   monotone (tanh) function of that readout, so probing `final_norm` for
   `derate_cmd` partially re-derives the action head. The informative facts
   are the *earlier* sites and the pooled probes against **outcome** labels
   (`del_ratio`, computed by the simulator, not by the network) — see
   `figs/interp/delmax2x2_B_pen_s1/probes_r2.png` from the CLI run, which
   shows the same ladder shape for outcomes.

The shuffle controls sit at ≈ 0 (mildly negative is expected: a probe fit to
noise generalizes slightly worse than the mean), so the evaluation is clean.
"""),

# ============================ 6. the direction ============================
("md", r"""
## 6. Stage 2b — from prediction to a *steering* direction

A probe answers "can I **read** the feature?" Steering needs something
subtly different: a direction to **write**. The pipeline uses the
**difference of class means**:

$$ v \;=\; \frac{\mu_{\text{conservative}} - \mu_{\text{aggressive}}}
{\lVert \mu_{\text{conservative}} - \mu_{\text{aggressive}} \rVert} $$

where the classes are the top and bottom quartiles of the (signed) label.
Why means rather than the probe's weight vector? Because the mean difference
is the *actual average displacement in activation space* between the two
behaviors. If activations decompose additively (residual stream!) as
"context + behavior component", the class-mean difference isolates the
behavior component, and *adding* it back is precisely the network's own
native operation. The ridge vector, by contrast, is optimized for prediction:
it is free to shrink along high-variance nuisance directions and lean on
low-variance correlates — great for reading, not necessarily the direction
along which the network *moves* when behavior changes.

Conventions baked into the artifacts:

- **Sign:** $+v$ points toward *more conservative* (higher derate).
- **Units:** `act_std` is the standard deviation of the data's projections
  onto $v$. Steering strengths are quoted in **σ-units** — "α = 2" means
  "push the stream 2 typical projection-spreads along $v$" — which makes
  strengths comparable across sites whose raw activation scales differ by
  ~50× (0.8 at `final_norm` vs ~38 at `resid_L1`).
"""),

("code", r"""
X = z["act_final_norm"][keep].reshape(-1, 128)
lo, hi = np.quantile(y, [0.25, 0.75])
aggressive, conservative = y <= lo, y >= hi

v = X[conservative].mean(axis=0) - X[aggressive].mean(axis=0)
v = v / np.linalg.norm(v)
act_std = float((X @ v).std())

stored = np.load(f"{DATA}/directions/direction_final_norm.npz")
print(f"live recompute vs stored artifact: cos = {float(v @ stored['vector']):+.5f}, "
      f"act_std {act_std:.3f} vs {float(stored['act_std']):.3f}")

ridge_w = Ridge(alpha=10.0).fit(X, y).coef_
cos_ridge = float(v @ ridge_w / np.linalg.norm(ridge_w))
print(f"cos(diff-of-means, ridge probe direction) = {cos_ridge:+.3f}")

proj = X @ v
fig, axes = plt.subplots(1, 2, figsize=(11, 3.7))
axes[0].hist(proj[aggressive], bins=40, alpha=0.7, color="C1",
             label="aggressive quartile")
axes[0].hist(proj[conservative], bins=40, alpha=0.7, color="C0",
             label="conservative quartile")
axes[0].set_xlabel("activation projection onto $v$")
axes[0].set_ylabel("tokens")
axes[0].set_title("class separation along the direction")
axes[0].legend(fontsize=8)

axes[1].scatter(proj, y, s=4, alpha=0.35, color="C0")
axes[1].set_xlabel("activation projection onto $v$")
axes[1].set_ylabel("derate command")
axes[1].set_title("projection tracks behavior across ALL tokens")
fig.tight_layout()
plt.show()
"""),

("md", r"""
Three readings of those numbers:

- **cos(live, stored) ≈ 1.000** — this notebook just re-derived the shipped
  Stage-2 artifact from raw data. No magic in the npz.
- **cos(diff-means, ridge) ≈ 0.34** — the *reading* direction and the
  *writing* direction genuinely differ. Both correlate with the label;
  they need not coincide, and the steering results below are the empirical
  reason the pipeline bets on the mean-difference.
- **The histogram separation is NOT evidence yet.** The classes were
  *defined* by the label, so separation along $v$ is guaranteed by
  construction. Everything so far — PCA, probes, this direction — is
  correlational. Whether the network actually *uses* $v$ is a causal
  question, and answering it is Stage 3.
"""),

# ============================ 7. steering =================================
("md", r"""
## 7. Stage 3 — steering: the causal experiment

**Activation addition**: during the forward pass, replace the site's
activation $x$ with $x + \alpha\,\sigma_{\text{act}}\, v$ (every token, every
step). If $v$ were merely correlated with conservativeness — a passenger, not
a driver — adding it would not systematically move behavior. If the
computation downstream of the site *reads* the $v$ component, behavior should
move, monotonically, in the direction the sign convention predicts. (The same
logic under the names *activation addition / steering vectors*: Turner et
al. 2023; *inference-time intervention*: Li et al. 2023; *representation
engineering*: Zou et al. 2023.)

`interp.hooks.SteeringHook` implements the write with the same hook
machinery as capture — return a *modified* output instead of `None` — plus
the tuple-rebuild subtlety for layer sites. One contract deserves emphasis:
at **α = 0 the hook returns `None`**, so PyTorch keeps the original tensor
and the baseline is **bitwise identical to the unhooked policy by
construction** (steer_eval additionally verifies this against a hookless
rollout). Baselines you get "by construction, not by luck" are the ones that
survive refactors.

Because the capture stores exact inputs, we can run the whole sweep
*offline* first: batch a few hundred captured states, sweep α, and watch the
derate channel of the policy's action head.
"""),

("code", r"""
from interp.hooks import SteeringHook

rng = np.random.default_rng(0)
idx = rng.choice(np.where(keep)[0], size=200, replace=False)
obs_b = torch.as_tensor(z["obs"][idx])
pos_b = torch.as_tensor(z["positions"][idx])
mask_b = torch.as_tensor(z["mask"][idx])
rec_b = torch.as_tensor(z["recep"][idx])
inf_b = torch.as_tensor(z["influ"][idx]) if actor.use_influence else None

alphas_off = np.linspace(-8, 8, 33)
derate_off, sat_off = [], []
with SteeringHook(actor, "final_norm", v, alpha=0.0) as hook:
    for a_sig in alphas_off:
        hook.set_alpha(float(a_sig) * act_std)       # sigma -> raw units
        with torch.no_grad():
            mean, _, _ = actor.forward(obs_b, pos_b, mask_b, rec_b, inf_b)
            act = squash(mean)[..., DERATE_COL]
        derate_off.append(float((0.1 * (act + 1)).mean()))   # -> command units
        sat_off.append(float((act.abs() > 0.99).float().mean()))
derate_off, sat_off = np.asarray(derate_off), np.asarray(sat_off)

i0 = int(np.argmin(np.abs(alphas_off)))              # alpha = 0 index
assert np.all(np.diff(derate_off) >= -1e-9), "expected a monotone dial"
print(f"33-alpha offline sweep on 200 captured states: monotone, "
      f"baseline derate {derate_off[i0]:.4f}")

clipped = sat_off > sat_off[i0] + 0.10               # steer_eval's flag rule
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(7.5, 5.8), sharex=True,
                               height_ratios=[2.2, 1.0])
for ax in (ax1, ax2):
    ax.fill_between(alphas_off, 0, 1, where=clipped,
                    transform=ax.get_xaxis_transform(),
                    color="C3", alpha=0.08, lw=0)
ax1.plot(alphas_off, derate_off, color="C0", lw=2)
ax1.plot(alphas_off[i0], derate_off[i0], "s", ms=9, mfc="none", color="C0",
         label=r"$\alpha=0$ (trained policy, exact)")
ax1.set_ylabel("mean derate command")
ax1.set_title("the dial: one direction, one coefficient "
              "(offline, 200 captured states)")
ax1.legend(fontsize=8, loc="upper left")
ax2.plot(alphas_off, sat_off, color="C0", lw=1.6)
ax2.set_ylabel("frac. tokens\ntanh-saturated")
ax2.set_xlabel(r"steering strength $\alpha$  [$\sigma$ of the projection]")
fig.tight_layout()
plt.show()
"""),

("md", r"""
### Reading the S-curve

- **It is a monotone dial.** Mean derate rises smoothly and strictly with α
  through the central regime — a single 128-dim direction, scaled by one
  coefficient, moves the safety behavior continuously in the predicted
  direction. That is the causal signature correlation alone could not give.
- **The flat shoulders are *clipping*, not steering** (red shading = tokens
  tanh-saturated beyond the α = 0 baseline + 10 pp, the same rule
  `steer_eval` uses). `fc_mean`'s output passes through `tanh`; push the
  pre-activation far enough and every token pins at an action limit. Beyond
  that point "more α" tells us nothing about the representation — the head
  is just railed.
- **The negative side saturates almost immediately.** The trained policy
  already sits near derate ≈ 0 (raw action ≈ −0.9, right against the −1
  floor), so *less* conservative has almost nowhere to go before clipping.
  This asymmetry is why negative α gets flagged early in the closed-loop
  sweep below — a nice example of reading an artifact's flags physically
  rather than as noise.
"""),

("md", r"""
### The real test: closed loop

The offline sweep froze the world: steered actions never fed back into the
simulator. But a steered policy *visits different states* — derate changes
wake deficits, loads, and the next observation. The closed-loop sweep
(`interp/steer_eval.py`, artifact loaded below) re-runs full DWM episodes
per α with **paired seeds** (identical turbulence boxes across α, so curves
differ only through the steering) and measures what actually matters:
realized derate, farm power vs the greedy baseline, and the DEL ratio.
"""),

("code", r"""
sw = np.load(f"{DATA}/steer/steer_final_norm_s0.npz")
sw_meta = json.loads(str(sw["metadata_json"]))
agg = json.loads(str(sw["agg_json"]))["steer"]
flagged = set(float(a) for a in sw["flagged_alphas"])
pairs = sorted((float(k), g) for k, g in agg.items())

print(f"closed-loop sweep: {sw_meta['episodes']} episodes x {sw_meta['steps']} "
      f"steps per alpha, paired seeds, site={sw_meta['site']}\n")
print(f"{'alpha':>6} {'derate':>8} {'P/P_base':>9} {'DEL ratio':>10} "
      f"{'sat(derate)':>12}   saturation-flagged")
for a, g in pairs:
    print(f"{a:+6.1f} {g['mean_derate']:8.3f} {g['power_ratio']:9.4f} "
          f"{g['del_ratio']:10.3f} {g['sat_derate']:12.2f}   "
          f"{'YES -- clipping regime' if a in flagged else 'no'}")

fig, ax = plt.subplots(figsize=(7.5, 4.2))
ax.plot(alphas_off, derate_off, color="C0", lw=2,
        label="offline replay (open loop, this notebook)")
ax.plot([p[0] for p in pairs], [p[1]["mean_derate"] for p in pairs], "o",
        color="C3", ms=7, label="closed-loop sweep (steer_eval.py)")
ax.set_xlabel(r"steering strength $\alpha$  [$\sigma$]")
ax.set_ylabel("mean derate command")
ax.set_title("open-loop prediction vs closed-loop reality")
ax.legend(fontsize=8)
fig.tight_layout()
plt.show()
"""),

("md", r"""
### What the closed loop shows

- **The dial survives feedback.** Mean derate is strictly monotone in α in
  the real loop too, and the offline curve predicted the closed-loop points
  remarkably well — evidence that the direction's effect is robust to the
  policy visiting the (moderately) shifted states it causes.
- **α = −4σ recovers the no-penalty phenotype.** Derate → 0.000, power ratio
  → 1.34, DEL ratio → 1.38: behaviorally this *is* `delmax2x2_A_nopen` — max
  power, ~38 % more fatigue load than baseline. Subtracting one direction
  from one layer's activations removes what the DEL penalty spent 400 k
  training steps building in. Conversely α = +4σ nearly saturates the derate
  budget (0.167 of 0.2 cap) and pushes the DEL ratio to ≈ 1.0.
- **The flags matter.** |α| ≥ 4 (and −2) exceed the baseline saturation by
  >10 pp: their *marginal* effects are clipping artifacts, so acceptance
  claims rest on the unflagged core around the origin plus the qualitative
  endpoint phenotypes. The sweep was **accepted** on exactly this basis:
  strict monotonicity, exact α = 0 baseline, and interpretable saturation.
"""),

("md", r"""
### The trade-off plane

The Stage-3 figure below (from the CLI run) replots the same sweep in the
plane that matters for operations — farm power ratio vs DEL ratio. Steering
traces a smooth power↔fatigue trade-off curve through the trained operating
point: an interpretability result expressed directly in engineering units.

![power-vs-DEL plane](figs/interp/delmax2x2_B_pen_s1/steer_plane_final_norm.png)

(For a randlim checkpoint, `steer_eval.py --limit-sweep` overlays the
*trained* limit-knob curve on this plane — the headline comparison of
"steering the representation" vs "using the designed control input". That
comparison is pending the 3×3 randlim training run.)
"""),

# ============================ 8. conclusions ==============================
("md", r"""
## 8. What we learned — and what we haven't

**Established, with causal evidence:**

- The agent's penalty-trained conservativeness is **assembled by the
  attention layers** (probe ladder: unreadable at `embed`, R² ≈ 0.75 at
  `final_norm`) — it is a function of cross-turbine context, not of any
  single turbine's sensors.
- At `final_norm` it behaves like a **single linear direction**: adding
  α·σ·v moves realized derating monotonically in closed loop, and
  **subtracting ~4σ cleanly removes the safety behavior**, recovering the
  no-penalty sibling's phenotype without touching a weight.
- The steering dial is honest about its own limits: the tanh-saturation
  monitor separates genuine representation-steering from action-head
  clipping.

**Caveats and open questions, roughly in order of importance:**

1. **Single direction vs distributed circuit.** Difference-of-means yields
   *one* vector; the true mechanism may be higher-dimensional (cos ≈ 0.34
   against the ridge direction hints the geometry is not trivial).
   Steering earlier sites (`resid_L0/L1`) would test how deep the handle
   goes — `final_norm` is one linear map from the action head, so steering
   there is only a *shallow* causal claim about the network's interior.
2. **Distribution shift under steering.** Large |α| pushes activations off
   the manifold the network was trained on; the closed-loop agreement here
   is reassuring but was measured on the training inflow (ws 10, TI 0.06)
   and one layout only.
3. **Control experiments pending.** Capture on `A_nopen` (does the direction
   even exist without the penalty? projecting its activations onto $v$ is
   the test), and the randlim question — is the goal-conditioned limit obs
   *the same* internal direction, i.e. does the trained knob and the steered
   knob coincide? (`--limit-sweep`, pending the 3×3 randlim run.)
4. **Per-turbine steering.** `SteeringHook(turbine_mask=...)` can steer only
   the waked row, only the front row, etc. — the turbine-clustered PCA says
   roles differ; per-role dials are the natural refinement.
5. **Phase 4.** The live slider: wire `set_alpha` into the interactive eval
   app as a real-time conservativeness knob next to the target-power slider.
"""),

# ============================ 9. reading + CLI ============================
("md", r"""
## 9. Further reading

- **Elhage et al. 2021, *A Mathematical Framework for Transformer Circuits***
  (transformer-circuits.pub) — the canonical residual-stream framing used in
  section 2; read at least "Residual streams as communication channels".
- **Alain & Bengio 2016, *Understanding intermediate layers using linear
  classifier probes*** (arXiv:1610.01644) — the origin of the probing
  methodology in section 5.
- **Turner et al. 2023, *Activation Addition*** (arXiv:2308.10248) — steering
  LLMs with difference-of-means vectors at inference time; the direct
  ancestor of Stage 3.
- **Li et al. 2023, *Inference-Time Intervention*** (arXiv:2306.03341) —
  steering along probe directions, with the probe/intervention-direction
  distinction from section 6.
- **Zou et al. 2023, *Representation Engineering*** (arXiv:2310.01405) — the
  survey-scale treatment of reading and controlling behavior via directions.
- **Elhage et al. 2022, *Toy Models of Superposition***
  (transformer-circuits.pub) — why "one feature = one direction" can fail;
  the theory behind caveat #1.
- **Park et al. 2023, *The Linear Representation Hypothesis***
  (arXiv:2311.03658) — what "features are directions" can even mean,
  formally.
"""),

("md", r"""
## Appendix: reproducing the expensive artifacts

Everything below runs from `TransformerSac/` and uses the repo venv. These
are the only steps that need the DWM simulator; each takes minutes-to-hours,
which is exactly why this notebook runs offline from their outputs.

```bash
# Stage 1 -- closed-loop capture (~1 h: Baseline_comp doubles the DWM cost)
../.venv/bin/python interp/capture_activations.py \
    --checkpoint runs/delmax2x2_B_pen_s1/checkpoints/step_400020.pt \
    --episodes 6 --steps 200 --warmup 20

# Stage 2 -- PCA figures, probes, direction npz per site (~1 min, offline)
../.venv/bin/python interp/analyze_directions.py \
    data/interp/delmax2x2_B_pen_s1/capture_limnone_s0.npz

# Stage 3 -- closed-loop steering sweep (~2 h for 7 alphas)
../.venv/bin/python interp/steer_eval.py \
    --checkpoint runs/delmax2x2_B_pen_s1/checkpoints/step_400020.pt \
    --direction data/interp/delmax2x2_B_pen_s1/directions/direction_final_norm.npz \
    --alphas -8,-4,-2,0,2,4,8 --episodes 2 --steps 100

# This notebook (~1-2 min, fully offline)
../.venv/bin/python interp/make_walkthrough.py
```
"""),
]


def build_notebook() -> nbformat.NotebookNode:
    nb = nbformat.v4.new_notebook()
    nb.metadata.kernelspec = {
        "name": "python3",
        "display_name": "Python 3 (paper-derating venv)",
        "language": "python",
    }
    nb.metadata.language_info = {"name": "python"}
    for kind, src in CELLS:
        src = src.strip("\n")
        if kind == "md":
            nb.cells.append(nbformat.v4.new_markdown_cell(src))
        elif kind == "code":
            nb.cells.append(nbformat.v4.new_code_cell(src))
        else:
            raise ValueError(f"Unknown cell kind {kind!r}")
    return nb


def main():
    nb = build_notebook()
    n_code = sum(1 for c in nb.cells if c.cell_type == "code")
    print(f"[walkthrough] {len(nb.cells)} cells ({n_code} code); executing with "
          f"kernel cwd = {TSAC_DIR}")
    t0 = time.time()
    client = NotebookClient(
        nb, timeout=600, kernel_name="python3",
        resources={"metadata": {"path": TSAC_DIR}},
    )
    client.execute()   # raises CellExecutionError on the first failing cell
    print(f"[walkthrough] executed in {time.time() - t0:.1f}s")

    nbformat.validate(nb)
    for i, cell in enumerate(nb.cells):
        for out in cell.get("outputs", []):
            if out.get("output_type") == "error":
                raise RuntimeError(f"Cell {i} has an error output: "
                                   f"{out.get('ename')}: {out.get('evalue')}")

    nbformat.write(nb, OUT_PATH)
    print(f"[walkthrough] wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
